In [ ]:
import pandas as pd
df=pd.read_csv(r'CCTD-2022_2024.csv')

Gender detection using ChatGPT 4

In [ ]:
# install open ai library
! pip install openai==0.28

Collecting openai==0.28
  Downloading openai-0.28.0-py3-none-any.whl (76 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.5/76.5 kB 1.9 MB/s eta 0:00:00
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.10/dist-packages (from openai==0.28) (2.31.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from openai==0.28) (4.66.4)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from openai==0.28) (3.9.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20->openai==0.28) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20->openai==0.28) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20->openai==0.28) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20->openai==0.28) (2024.6.2)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->openai==0.28) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->openai==0.28) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->openai==0.28) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->openai==0.28) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->openai==0.28) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->openai==0.28) (4.0.3)
Installing collected packages: openai
Successfully installed openai-0.28.0

In [ ]:
# import openai
from time import time , sleep
import pandas as pd
import numpy as np
import json
import openai

In [ ]:
openai.api_key = 'Your_Key'

In [ ]:
def get_completion(prompt: str, model="gpt-4-turbo"):
        # say the role of model
        messages = [
            {"role": "system", "content": "suppose you're gender classifier model"},
            {"role": "user", "content": prompt},
        ]
        t0 = time()
        response = openai.ChatCompletion.create(
            model=model,
            messages=messages,
            temperature=0,  # this is the degree of randomness of the model's output
            max_tokens=650,
        )
        t1 = time()
        usage = response.usage
        usage = {**usage, "time": f"{t1-t0:.2f} seconds"}
        print(usage)

        return response.choices[0].message["content"]

In [ ]:
# Prompt Template
prompt_template = """
You are an expert gender classifier. Your task is to classify the gender of these names into one of three categories: "female", "male" or "unknown".
```
{comment}
```
Your response should be one of the following labels: female, male, unknown.
"""

In [ ]:
text = df['name'].to_list()

In [ ]:
awnser = []

In [ ]:
stopIter = len(text)
counter = 0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
while True:
  try:
    if counter >= stopIter:
      break
    res = get_completion(prompt_template.format(comment=text[counter]))
    # append response to text file
    f = open("/content/drive/MyDrive/gender.txt", "a") #set your drive path
    f.write('\n')
    f.write(str(counter)+' : ' + res)
    awnser.append(res)
    f.write(',')
    f.close()
    counter +=1
  except Exception  as e:
    print(e)
    # for limit rate wait for 20 seconds
    sleep(20)

{'prompt_tokens': 81, 'completion_tokens': 1, 'total_tokens': 82, 'time': '0.55 seconds'}
{'prompt_tokens': 81, 'completion_tokens': 1, 'total_tokens': 82, 'time': '0.47 seconds'}
{'prompt_tokens': 81, 'completion_tokens': 1, 'total_tokens': 82, 'time': '0.46 seconds'}
{'prompt_tokens': 88, 'completion_tokens': 1, 'total_tokens': 89, 'time': '0.43 seconds'}
{'prompt_tokens': 88, 'completion_tokens': 1, 'total_tokens': 89, 'time': '0.51 seconds'}
{'prompt_tokens': 84, 'completion_tokens': 1, 'total_tokens': 85, 'time': '0.45 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.47 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.44 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.44 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.48 seconds'}
{'prompt_tokens': 85, 'completion_tokens': 1, 'total_tokens': 86, 'time': '0.61 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.62 seconds'}
{'prompt_tokens': 87, 'completion_tokens': 1, 'total_tokens': 88, 'time': '0.52 seconds'}
{'prompt_tokens': 87, 'completion_tokens': 1, 'total_tokens': 88, 'time': '0.58 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.56 seconds'}
{'prompt_tokens': 74, 'completion_tokens': 1, 'total_tokens': 75, 'time': '0.48 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.48 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.56 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.92 seconds'}
{'prompt_tokens': 75, 'completion_tokens': 1, 'total_tokens': 76, 'time': '0.48 seconds'}
{'prompt_tokens': 75, 'completion_tokens': 1, 'total_tokens': 76, 'time': '0.46 seconds'}
{'prompt_tokens': 75, 'completion_tokens': 1, 'total_tokens': 76, 'time': '0.49 seconds'}
{'prompt_tokens': 86, 'completion_tokens': 1, 'total_tokens': 87, 'time': '0.45 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.58 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.42 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.57 seconds'}
{'prompt_tokens': 74, 'completion_tokens': 1, 'total_tokens': 75, 'time': '0.46 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.56 seconds'}
{'prompt_tokens': 75, 'completion_tokens': 1, 'total_tokens': 76, 'time': '0.53 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.79 seconds'}
{'prompt_tokens': 75, 'completion_tokens': 1, 'total_tokens': 76, 'time': '0.51 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.45 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.87 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.64 seconds'}
{'prompt_tokens': 104, 'completion_tokens': 1, 'total_tokens': 105, 'time': '0.52 seconds'}
{'prompt_tokens': 82, 'completion_tokens': 1, 'total_tokens': 83, 'time': '0.54 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.48 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.43 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.55 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.44 seconds'}
{'prompt_tokens': 79, 'completion_tokens': 1, 'total_tokens': 80, 'time': '0.49 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.46 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.52 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.42 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.54 seconds'}
{'prompt_tokens': 74, 'completion_tokens': 1, 'total_tokens': 75, 'time': '0.47 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.59 seconds'}
{'prompt_tokens': 79, 'completion_tokens': 1, 'total_tokens': 80, 'time': '0.41 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.46 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.55 seconds'}
{'prompt_tokens': 80, 'completion_tokens': 1, 'total_tokens': 81, 'time': '0.45 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.56 seconds'}
{'prompt_tokens': 75, 'completion_tokens': 1, 'total_tokens': 76, 'time': '0.82 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.58 seconds'}
{'prompt_tokens': 87, 'completion_tokens': 1, 'total_tokens': 88, 'time': '0.60 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.39 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.40 seconds'}
{'prompt_tokens': 83, 'completion_tokens': 1, 'total_tokens': 84, 'time': '2.28 seconds'}
{'prompt_tokens': 83, 'completion_tokens': 1, 'total_tokens': 84, 'time': '0.56 seconds'}
{'prompt_tokens': 84, 'completion_tokens': 1, 'total_tokens': 85, 'time': '0.51 seconds'}
{'prompt_tokens': 94, 'completion_tokens': 1, 'total_tokens': 95, 'time': '0.41 seconds'}
{'prompt_tokens': 94, 'completion_tokens': 1, 'total_tokens': 95, 'time': '0.61 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.63 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.62 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.53 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.42 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.40 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.54 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.51 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.45 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.51 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.50 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.49 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.57 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.52 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.49 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.56 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.59 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.58 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.46 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.59 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.50 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.46 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.48 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.61 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.48 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.45 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.45 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.51 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.46 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.41 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.40 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.43 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.60 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.67 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.52 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.51 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.43 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.51 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.46 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.51 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.50 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.56 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.56 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.56 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.45 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.45 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.57 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.47 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.43 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.47 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.47 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.57 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.48 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.47 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.53 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.51 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.52 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.49 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.47 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.51 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.52 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.46 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.45 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.44 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.52 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.54 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.53 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.47 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.52 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.49 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.48 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.55 seconds'}
{'prompt_tokens': 75, 'completion_tokens': 1, 'total_tokens': 76, 'time': '0.53 seconds'}
{'prompt_tokens': 83, 'completion_tokens': 1, 'total_tokens': 84, 'time': '0.48 seconds'}
{'prompt_tokens': 102, 'completion_tokens': 1, 'total_tokens': 103, 'time': '0.46 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.59 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.88 seconds'}
{'prompt_tokens': 75, 'completion_tokens': 1, 'total_tokens': 76, 'time': '0.53 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.48 seconds'}
{'prompt_tokens': 82, 'completion_tokens': 1, 'total_tokens': 83, 'time': '0.55 seconds'}
{'prompt_tokens': 83, 'completion_tokens': 1, 'total_tokens': 84, 'time': '0.46 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.49 seconds'}
{'prompt_tokens': 80, 'completion_tokens': 1, 'total_tokens': 81, 'time': '0.52 seconds'}
{'prompt_tokens': 81, 'completion_tokens': 1, 'total_tokens': 82, 'time': '0.44 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.50 seconds'}
{'prompt_tokens': 107, 'completion_tokens': 1, 'total_tokens': 108, 'time': '0.54 seconds'}
{'prompt_tokens': 75, 'completion_tokens': 1, 'total_tokens': 76, 'time': '0.59 seconds'}
{'prompt_tokens': 80, 'completion_tokens': 1, 'total_tokens': 81, 'time': '0.48 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.44 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.47 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.47 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.43 seconds'}
{'prompt_tokens': 82, 'completion_tokens': 1, 'total_tokens': 83, 'time': '0.54 seconds'}
{'prompt_tokens': 79, 'completion_tokens': 1, 'total_tokens': 80, 'time': '0.44 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.53 seconds'}
{'prompt_tokens': 80, 'completion_tokens': 1, 'total_tokens': 81, 'time': '0.44 seconds'}
{'prompt_tokens': 80, 'completion_tokens': 1, 'total_tokens': 81, 'time': '0.55 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.55 seconds'}
{'prompt_tokens': 88, 'completion_tokens': 1, 'total_tokens': 89, 'time': '0.57 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.64 seconds'}
{'prompt_tokens': 81, 'completion_tokens': 1, 'total_tokens': 82, 'time': '0.55 seconds'}
{'prompt_tokens': 90, 'completion_tokens': 1, 'total_tokens': 91, 'time': '0.43 seconds'}
{'prompt_tokens': 82, 'completion_tokens': 1, 'total_tokens': 83, 'time': '0.45 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.57 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.47 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.55 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.44 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.43 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.46 seconds'}
{'prompt_tokens': 89, 'completion_tokens': 1, 'total_tokens': 90, 'time': '0.54 seconds'}
{'prompt_tokens': 89, 'completion_tokens': 1, 'total_tokens': 90, 'time': '0.41 seconds'}
{'prompt_tokens': 89, 'completion_tokens': 1, 'total_tokens': 90, 'time': '0.42 seconds'}
{'prompt_tokens': 75, 'completion_tokens': 1, 'total_tokens': 76, 'time': '0.48 seconds'}
{'prompt_tokens': 82, 'completion_tokens': 1, 'total_tokens': 83, 'time': '0.45 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.61 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.48 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.46 seconds'}
{'prompt_tokens': 101, 'completion_tokens': 1, 'total_tokens': 102, 'time': '0.48 seconds'}
{'prompt_tokens': 74, 'completion_tokens': 1, 'total_tokens': 75, 'time': '0.43 seconds'}
{'prompt_tokens': 91, 'completion_tokens': 1, 'total_tokens': 92, 'time': '0.61 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.50 seconds'}
{'prompt_tokens': 84, 'completion_tokens': 1, 'total_tokens': 85, 'time': '0.54 seconds'}
{'prompt_tokens': 81, 'completion_tokens': 1, 'total_tokens': 82, 'time': '0.51 seconds'}
{'prompt_tokens': 74, 'completion_tokens': 1, 'total_tokens': 75, 'time': '0.60 seconds'}
{'prompt_tokens': 81, 'completion_tokens': 1, 'total_tokens': 82, 'time': '0.53 seconds'}
{'prompt_tokens': 81, 'completion_tokens': 1, 'total_tokens': 82, 'time': '0.58 seconds'}
{'prompt_tokens': 81, 'completion_tokens': 1, 'total_tokens': 82, 'time': '0.59 seconds'}
{'prompt_tokens': 81, 'completion_tokens': 1, 'total_tokens': 82, 'time': '0.44 seconds'}
{'prompt_tokens': 81, 'completion_tokens': 1, 'total_tokens': 82, 'time': '0.46 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.52 seconds'}
{'prompt_tokens': 75, 'completion_tokens': 1, 'total_tokens': 76, 'time': '0.56 seconds'}
{'prompt_tokens': 94, 'completion_tokens': 1, 'total_tokens': 95, 'time': '0.64 seconds'}
{'prompt_tokens': 106, 'completion_tokens': 1, 'total_tokens': 107, 'time': '0.48 seconds'}
{'prompt_tokens': 83, 'completion_tokens': 1, 'total_tokens': 84, 'time': '0.57 seconds'}
{'prompt_tokens': 80, 'completion_tokens': 1, 'total_tokens': 81, 'time': '0.66 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.51 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.59 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.57 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.45 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.48 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.55 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '1.30 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.56 seconds'}
{'prompt_tokens': 102, 'completion_tokens': 1, 'total_tokens': 103, 'time': '0.56 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.49 seconds'}
{'prompt_tokens': 79, 'completion_tokens': 1, 'total_tokens': 80, 'time': '0.45 seconds'}
{'prompt_tokens': 75, 'completion_tokens': 1, 'total_tokens': 76, 'time': '0.50 seconds'}
{'prompt_tokens': 77, 'completion_tokens': 1, 'total_tokens': 78, 'time': '0.56 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.47 seconds'}
{'prompt_tokens': 105, 'completion_tokens': 1, 'total_tokens': 106, 'time': '0.56 seconds'}
{'prompt_tokens': 88, 'completion_tokens': 1, 'total_tokens': 89, 'time': '0.49 seconds'}
{'prompt_tokens': 82, 'completion_tokens': 1, 'total_tokens': 83, 'time': '0.44 seconds'}
{'prompt_tokens': 79, 'completion_tokens': 1, 'total_tokens': 80, 'time': '0.48 seconds'}
{'prompt_tokens': 85, 'completion_tokens': 1, 'total_tokens': 86, 'time': '0.48 seconds'}
{'prompt_tokens': 75, 'completion_tokens': 1, 'total_tokens': 76, 'time': '0.44 seconds'}
{'prompt_tokens': 108, 'completion_tokens': 1, 'total_tokens': 109, 'time': '0.44 seconds'}
{'prompt_tokens': 80, 'completion_tokens': 1, 'total_tokens': 81, 'time': '0.57 seconds'}
{'prompt_tokens': 84, 'completion_tokens': 1, 'total_tokens': 85, 'time': '0.58 seconds'}
{'prompt_tokens': 78, 'completion_tokens': 1, 'total_tokens': 79, 'time': '0.47 seconds'}
{'prompt_tokens': 76, 'completion_tokens': 1, 'total_tokens': 77, 'time': '0.51 seconds'}
{'prompt_tokens': 106, 'completion_tokens': 1, 'total_tokens': 107, 'time': '0.53 seconds'}

In [ ]:
exist = pd.read_csv(r'gender.txt',header=None)

In [ ]:
exist

                   0   1
0         0 : female NaN
1         1 : female NaN
2         2 : female NaN
3        3 : unknown NaN
4        4 : unknown NaN
...              ...  ..
2898  2898 : unknown NaN
2899  2899 : unknown NaN
2900  2900 : unknown NaN
2901     2901 : male NaN
2902     2902 : male NaN

[2903 rows x 2 columns]

Age Detection using De
epFace

In [ ]:
!pip install deepface

Collecting deepface
  Downloading deepface-0.0.92-py3-none-any.whl (105 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.5/105.5 kB 2.9 MB/s eta 0:00:00
Requirement already satisfied: requests>=2.27.1 in /usr/local/lib/python3.10/dist-packages (from deepface) (2.31.0)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from deepface) (1.25.2)
Requirement already satisfied: pandas>=0.23.4 in /usr/local/lib/python3.10/dist-packages (from deepface) (2.0.3)
Requirement already satisfied: gdown>=3.10.1 in /usr/local/lib/python3.10/dist-packages (from deepface) (5.1.0)
Requirement already satisfied: tqdm>=4.30.0 in /usr/local/lib/python3.10/dist-packages (from deepface) (4.66.4)
Requirement already satisfied: Pillow>=5.2.0 in /usr/local/lib/python3.10/dist-packages (from deepface) (9.4.0)
Requirement already satisfied: opencv-python>=4.5.5.64 in /usr/local/lib/python3.10/dist-packages (from deepface) (4.8.0.76)
Requirement already satisfied: tensorflow>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from deepface) (2.15.0)
Requirement already satisfied: keras>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from deepface) (2.15.0)
Requirement already satisfied: Flask>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from deepface) (2.2.5)
Collecting mtcnn>=0.1.0 (from deepface)
  Downloading mtcnn-0.1.1-py3-none-any.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 8.8 MB/s eta 0:00:00
Collecting retina-face>=0.0.1 (from deepface)
  Downloading retina_face-0.0.17-py3-none-any.whl (25 kB)
Collecting fire>=0.4.0 (from deepface)
  Downloading fire-0.6.0.tar.gz (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.4/88.4 kB 10.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting gunicorn>=20.1.0 (from deepface)
  Downloading gunicorn-22.0.0-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.4/84.4 kB 9.4 MB/s eta 0:00:00
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from fire>=0.4.0->deepface) (1.16.0)
Requirement already satisfied: termcolor in /usr/local/lib/python3.10/dist-packages (from fire>=0.4.0->deepface) (2.4.0)
Requirement already satisfied: Werkzeug>=2.2.2 in /usr/local/lib/python3.10/dist-packages (from Flask>=1.1.2->deepface) (3.0.3)
Requirement already satisfied: Jinja2>=3.0 in /usr/local/lib/python3.10/dist-packages (from Flask>=1.1.2->deepface) (3.1.4)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.10/dist-packages (from Flask>=1.1.2->deepface) (2.2.0)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.10/dist-packages (from Flask>=1.1.2->deepface) (8.1.7)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from gdown>=3.10.1->deepface) (4.12.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from gdown>=3.10.1->deepface) (3.14.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from gunicorn>=20.1.0->deepface) (24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.23.4->deepface) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.23.4->deepface) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.23.4->deepface) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.27.1->deepface) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.27.1->deepface) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.27.1->deepface) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.27.1->deepface) (2024.6.2)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (0.5.4)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (3.9.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (18.1.1)
Requirement already satisfied: ml-dtypes~=0.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (0.2.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (3.3.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (3.20.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (67.7.2)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (4.12.2)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (0.37.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (1.64.1)
Requirement already satisfied: tensorboard<2.16,>=2.15 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (2.15.2)
Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (2.15.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow>=1.9.0->deepface) (0.43.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2>=3.0->Flask>=1.1.2->deepface) (2.1.5)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (2.27.0)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (1.2.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (3.6)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (0.7.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->gdown>=3.10.1->deepface) (2.5)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from requests>=2.27.1->deepface) (1.7.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (5.3.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (0.4.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (1.3.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (0.6.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (3.2.2)
Building wheels for collected packages: fire
  Building wheel for fire (setup.py) ... done
  Created wheel for fire: filename=fire-0.6.0-py2.py3-none-any.whl size=117029 sha256=705c87d70c4c823a0f2bc71c3b825debce4dcddf2097536abe230ca059562b13
  Stored in directory: /root/.cache/pip/wheels/d6/6d/5d/5b73fa0f46d01a793713f8859201361e9e581ced8c75e5c6a3
Successfully built fire
Installing collected packages: gunicorn, fire, mtcnn, retina-face, deepface
Successfully installed deepface-0.0.92 fire-0.6.0 gunicorn-22.0.0 mtcnn-0.1.1 retina-face-0.0.17

In [ ]:
!pip install requests Pillow pandas

Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (2.31.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (9.4.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests) (2024.6.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

# face detector

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving all_images.zip to all_images.zip

In [ ]:
import zipfile
import os

zip_file_name = 'all_images.zip'
with zipfile.ZipFile(zip_file_name, 'r') as zip_ref:
    zip_ref.extractall('/content')

In [ ]:
!pip install opencv-python

In [ ]:
!pip install Pillow

Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (9.4.0)

In [ ]:
import os
from PIL import Image
import cv2

# Function to convert an image to JPG format and resize it
def convert_and_resize_image(image_path, output_path, size=(400, 400)):
    with Image.open(image_path) as img:
        img = img.convert('RGB')  # Convert to RGB mode
        img = img.resize(size)    # Resize image
        img.save(output_path, 'JPEG')

# Function to check if a face is in the photo
def is_face_in_photo(image_path):
    # Load the pre-trained Haar Cascade classifier for face detection
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

    # Read the image
    img = cv2.imread(image_path)
    if img is None:
        print(f"Failed to load image: {image_path}")
        return False

    # Convert the image to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Detect faces in the image
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))

    # Check if faces are detected
    if len(faces) > 0:
        print(f"Faces detected in {image_path}: {faces}")
        return True
    else:
        print(f"No face detected in {image_path}")
        return False

# Directory where the photos are stored
photos_directory = '/content/all_images'  # Replace with the actual directory containing the photos
converted_directory = '/content/converted_images'  # Directory to save converted images

# Create the directory if it does not exist
if not os.path.exists(converted_directory):
    os.makedirs(converted_directory)

# List all files in the photos directory
files = os.listdir(photos_directory)

# Convert and resize all files to JPG format
for file_name in files:
    image_path = os.path.join(photos_directory, file_name)
    # Generate new file name for JPG
    new_file_name = os.path.splitext(file_name)[0] + '.jpg'
    output_path = os.path.join(converted_directory, new_file_name)
    try:
        convert_and_resize_image(image_path, output_path)
    except Exception as e:
        print(f"Failed to convert and resize {image_path} to JPG: {e}")

# Initialize the results list with NaNs
results = [np.nan] * 2903  

# Process each converted file
converted_files = os.listdir(converted_directory)
for file_name in converted_files:
    # Check if the file name is a number and within the specified range
    if file_name.split('.')[0].isdigit() and 0 <= int(file_name.split('.')[0]) <= 2902:
        index = int(file_name.split('.')[0])
        image_path = os.path.join(converted_directory, file_name)
        # Check for face in the photo
        if is_face_in_photo(image_path):
            results[index] = 'face'
        else:
            results[index] = 'no-face'
    else:
        print(f"Skipping file: {file_name}")

# Create a list of photos that do not exist in the results
not_exist_list = [index for index, result in enumerate(results) if pd.isna(result)]

# Output the results
print("Results List:", results)
print("Photos that do not exist in the list:", not_exist_list)

# Count 'face' values in the results list
face_count = results.count('face')
print(f"Number of photos with faces detected: {face_count}")

df = pd.DataFrame(results, columns=['face_detect'])

print(df)

Failed to convert and resize /content/all_images/all_images to JPG: [Errno 21] Is a directory: '/content/all_images/all_images'
No face detected in /content/converted_images/1190.jpg
No face detected in /content/converted_images/1060.jpg
Faces detected in /content/converted_images/2404.jpg: [[104  83 177 177]]
No face detected in /content/converted_images/1486.jpg
No face detected in /content/converted_images/640.jpg
Faces detected in /content/converted_images/1376.jpg: [[258  76  59  59]]
No face detected in /content/converted_images/1298.jpg
No face detected in /content/converted_images/1726.jpg
No face detected in /content/converted_images/1685.jpg
Faces detected in /content/converted_images/2271.jpg: [[180  63  46  46]]
No face detected in /content/converted_images/2077.jpg
No face detected in /content/converted_images/2652.jpg
No face detected in /content/converted_images/408.jpg
No face detected in /content/converted_images/55.jpg
Faces detected in /content/converted_images/2345.jpg: [[ 67  40 222 222]]
Faces detected in /content/converted_images/63.jpg: [[ 94  89 193 193]]
No face detected in /content/converted_images/1188.jpg
Faces detected in /content/converted_images/1557.jpg: [[  3 126  42  42]
 [169  67  93  93]]
Faces detected in /content/converted_images/101.jpg: [[ 94  89 193 193]]
Faces detected in /content/converted_images/435.jpg: [[ 24  40 260 260]]
Faces detected in /content/converted_images/577.jpg: [[115  92 176 176]]
No face detected in /content/converted_images/2736.jpg
No face detected in /content/converted_images/645.jpg
Faces detected in /content/converted_images/441.jpg: [[244  67  88  88]]
Faces detected in /content/converted_images/2096.jpg: [[102  81 226 226]]
No face detected in /content/converted_images/2521.jpg
No face detected in /content/converted_images/1133.jpg
No face detected in /content/converted_images/2011.jpg
No face detected in /content/converted_images/2415.jpg
Faces detected in /content/converted_images/1847.jpg: [[111  77 183 183]]
No face detected in /content/converted_images/1607.jpg
No face detected in /content/converted_images/2438.jpg
No face detected in /content/converted_images/841.jpg
Faces detected in /content/converted_images/2071.jpg: [[114  80 126 126]]
Faces detected in /content/converted_images/94.jpg: [[ 94  89 193 193]]
No face detected in /content/converted_images/850.jpg
No face detected in /content/converted_images/499.jpg
Faces detected in /content/converted_images/2178.jpg: [[182  99 129 129]]
No face detected in /content/converted_images/2418.jpg
No face detected in /content/converted_images/2183.jpg
Faces detected in /content/converted_images/1836.jpg: [[156 116 106 106]]
No face detected in /content/converted_images/2852.jpg
Faces detected in /content/converted_images/2326.jpg: [[276 174  58  58]]
Faces detected in /content/converted_images/2608.jpg: [[111  94 168 168]]
No face detected in /content/converted_images/1719.jpg
No face detected in /content/converted_images/2719.jpg
Faces detected in /content/converted_images/2073.jpg: [[ 61 152  96  96]]
Faces detected in /content/converted_images/1214.jpg: [[ 69  96 232 232]]
Faces detected in /content/converted_images/2560.jpg: [[114 112 142 142]]
Faces detected in /content/converted_images/2697.jpg: [[167  35  78  78]
 [270 191  59  59]]
Faces detected in /content/converted_images/1604.jpg: [[139  48 114 114]]
No face detected in /content/converted_images/2027.jpg
Faces detected in /content/converted_images/591.jpg: [[132  89  79  79]]
No face detected in /content/converted_images/201.jpg
No face detected in /content/converted_images/2165.jpg
Faces detected in /content/converted_images/1037.jpg: [[143  67 132 132]]
Faces detected in /content/converted_images/1295.jpg: [[199  80 141 141]]
Faces detected in /content/converted_images/2020.jpg: [[149  63 110 110]
 [220 300  68  68]]
No face detected in /content/converted_images/2008.jpg
Faces detected in /content/converted_images/946.jpg: [[103 135 218 218]]
No face detected in /content/converted_images/1088.jpg
Faces detected in /content/converted_images/1832.jpg: [[160 164  59  59]]
No face detected in /content/converted_images/1030.jpg
Faces detected in /content/converted_images/2802.jpg: [[118 248  68  68]]
No face detected in /content/converted_images/487.jpg
Faces detected in /content/converted_images/1777.jpg: [[165  18 124 124]]
No face detected in /content/converted_images/2630.jpg
No face detected in /content/converted_images/1262.jpg
No face detected in /content/converted_images/2514.jpg
Faces detected in /content/converted_images/69.jpg: [[ 94  89 193 193]]
No face detected in /content/converted_images/1456.jpg
Faces detected in /content/converted_images/989.jpg: [[157  47  88  88]]
No face detected in /content/converted_images/753.jpg
No face detected in /content/converted_images/347.jpg
Faces detected in /content/converted_images/2526.jpg: [[225 280  52  52]]
No face detected in /content/converted_images/1350.jpg
No face detected in /content/converted_images/1915.jpg
No face detected in /content/converted_images/1718.jpg
Faces detected in /content/converted_images/776.jpg: [[ 37  54 302 302]]
Faces detected in /content/converted_images/2870.jpg: [[129   8  85  85]]
Faces detected in /content/converted_images/720.jpg: [[333 203  56  56]]
No face detected in /content/converted_images/451.jpg
Faces detected in /content/converted_images/2216.jpg: [[ 86  71 193 193]]
Faces detected in /content/converted_images/2643.jpg: [[ 44  60 330 330]
 [181 202  56  56]]
Faces detected in /content/converted_images/940.jpg: [[112 103 189 189]]
No face detected in /content/converted_images/697.jpg
Faces detected in /content/converted_images/2841.jpg: [[121 124  97  97]]
No face detected in /content/converted_images/1791.jpg
Faces detected in /content/converted_images/1135.jpg: [[ 21  15 272 272]]
No face detected in /content/converted_images/713.jpg
Faces detected in /content/converted_images/2256.jpg: [[99 93 90 90]]
Faces detected in /content/converted_images/30.jpg: [[ 80  77 239 239]]
No face detected in /content/converted_images/1644.jpg
No face detected in /content/converted_images/379.jpg
No face detected in /content/converted_images/2378.jpg
Faces detected in /content/converted_images/264.jpg: [[254  27  77  77]
 [144 284  60  60]]
Faces detected in /content/converted_images/1484.jpg: [[129 155  83  83]]
No face detected in /content/converted_images/2681.jpg
Faces detected in /content/converted_images/389.jpg: [[169 111 109 109]]
Faces detected in /content/converted_images/423.jpg: [[238 212  76  76]]
No face detected in /content/converted_images/2614.jpg
No face detected in /content/converted_images/1797.jpg
No face detected in /content/converted_images/1620.jpg
Faces detected in /content/converted_images/1329.jpg: [[ 37 184  96  96]]
No face detected in /content/converted_images/1560.jpg
No face detected in /content/converted_images/1483.jpg
No face detected in /content/converted_images/2334.jpg
No face detected in /content/converted_images/2005.jpg
No face detected in /content/converted_images/1061.jpg
No face detected in /content/converted_images/1656.jpg
Faces detected in /content/converted_images/2278.jpg: [[142 223  70  70]]
No face detected in /content/converted_images/831.jpg
No face detected in /content/converted_images/1441.jpg
Faces detected in /content/converted_images/374.jpg: [[100  60 294 294]]
Faces detected in /content/converted_images/170.jpg: [[109 150  49  49]]
No face detected in /content/converted_images/2250.jpg
Faces detected in /content/converted_images/571.jpg: [[ 42 149  38  38]
 [ 33 211  54  54]]
No face detected in /content/converted_images/166.jpg
No face detected in /content/converted_images/2711.jpg
No face detected in /content/converted_images/906.jpg
No face detected in /content/converted_images/414.jpg
No face detected in /content/converted_images/1531.jpg
No face detected in /content/converted_images/1353.jpg
No face detected in /content/converted_images/2076.jpg
No face detected in /content/converted_images/2090.jpg
Faces detected in /content/converted_images/277.jpg: [[ 88  60 231 231]]
No face detected in /content/converted_images/1759.jpg
No face detected in /content/converted_images/1951.jpg
Faces detected in /content/converted_images/1971.jpg: [[ 54 117  60  60]]
No face detected in /content/converted_images/2582.jpg
No face detected in /content/converted_images/2462.jpg
Faces detected in /content/converted_images/1204.jpg: [[ 96  56 257 257]]
No face detected in /content/converted_images/2822.jpg
Faces detected in /content/converted_images/1448.jpg: [[130 311  51  51]]
Faces detected in /content/converted_images/127.jpg: [[ 94  89 193 193]]
Faces detected in /content/converted_images/2364.jpg: [[ 96  30  94  94]
 [132 199  73  73]]
Faces detected in /content/converted_images/2363.jpg: [[ 96  30  94  94]
 [132 199  73  73]]
No face detected in /content/converted_images/2365.jpg
Faces detected in /content/converted_images/100.jpg: [[ 94  89 193 193]]
Faces detected in /content/converted_images/2622.jpg: [[112  80 207 207]
 [112 161 173 173]]
Faces detected in /content/converted_images/1765.jpg: [[ 26 226  53  53]]
No face detected in /content/converted_images/544.jpg
No face detected in /content/converted_images/486.jpg
No face detected in /content/converted_images/2737.jpg
No face detected in /content/converted_images/2674.jpg
Faces detected in /content/converted_images/2504.jpg: [[140  92 123 123]]
Faces detected in /content/converted_images/432.jpg: [[ 51  40 215 215]]
Faces detected in /content/converted_images/2164.jpg: [[105  89 225 225]]
No face detected in /content/converted_images/2506.jpg
No face detected in /content/converted_images/2743.jpg
No face detected in /content/converted_images/1248.jpg
No face detected in /content/converted_images/1622.jpg
No face detected in /content/converted_images/1247.jpg
No face detected in /content/converted_images/1050.jpg
No face detected in /content/converted_images/1669.jpg
No face detected in /content/converted_images/1185.jpg
Faces detected in /content/converted_images/336.jpg: [[ 77  89 269 269]]
Faces detected in /content/converted_images/573.jpg: [[113 116 220 220]]
No face detected in /content/converted_images/2591.jpg
Faces detected in /content/converted_images/517.jpg: [[ 52  99 293 293]]
No face detected in /content/converted_images/1822.jpg
No face detected in /content/converted_images/36.jpg
No face detected in /content/converted_images/658.jpg
Faces detected in /content/converted_images/2158.jpg: [[119  70 173 173]
 [132 213 142 142]]
Faces detected in /content/converted_images/1742.jpg: [[ 87  86 191 191]]
No face detected in /content/converted_images/458.jpg
Faces detected in /content/converted_images/2014.jpg: [[ 70  46 196 196]]
No face detected in /content/converted_images/1576.jpg
No face detected in /content/converted_images/159.jpg
No face detected in /content/converted_images/854.jpg
No face detected in /content/converted_images/2805.jpg
No face detected in /content/converted_images/1998.jpg
Faces detected in /content/converted_images/1280.jpg: [[ 14  82  65  65]
 [ 58 153  91  91]]
No face detected in /content/converted_images/2432.jpg
Faces detected in /content/converted_images/1097.jpg: [[ 98  78 149 149]]
Faces detected in /content/converted_images/1251.jpg: [[180 237  62  62]]
Faces detected in /content/converted_images/1116.jpg: [[ 75  93 193 193]]
No face detected in /content/converted_images/1617.jpg
No face detected in /content/converted_images/471.jpg
No face detected in /content/converted_images/1643.jpg
Faces detected in /content/converted_images/958.jpg: [[122  37 166 166]]
No face detected in /content/converted_images/2135.jpg
No face detected in /content/converted_images/2579.jpg
Faces detected in /content/converted_images/2359.jpg: [[265 225  58  58]]
No face detected in /content/converted_images/1414.jpg
No face detected in /content/converted_images/1516.jpg
Faces detected in /content/converted_images/514.jpg: [[ 52  99 293 293]]
No face detected in /content/converted_images/2726.jpg
Faces detected in /content/converted_images/1360.jpg: [[ 65  91 132 132]]
No face detected in /content/converted_images/2851.jpg
No face detected in /content/converted_images/1443.jpg
Faces detected in /content/converted_images/1886.jpg: [[ 59 104 202 202]]
No face detected in /content/converted_images/2712.jpg
Faces detected in /content/converted_images/1722.jpg: [[125  60 152 152]]
No face detected in /content/converted_images/2231.jpg
Faces detected in /content/converted_images/2091.jpg: [[ 47  69 304 304]]
No face detected in /content/converted_images/1171.jpg
No face detected in /content/converted_images/620.jpg
Faces detected in /content/converted_images/1675.jpg: [[ 65 177  96  96]]
No face detected in /content/converted_images/2657.jpg
No face detected in /content/converted_images/1876.jpg
No face detected in /content/converted_images/1518.jpg
No face detected in /content/converted_images/1552.jpg
No face detected in /content/converted_images/1183.jpg
No face detected in /content/converted_images/1449.jpg
Faces detected in /content/converted_images/365.jpg: [[210  71 105 105]]
No face detected in /content/converted_images/1544.jpg
No face detected in /content/converted_images/2836.jpg
Faces detected in /content/converted_images/2338.jpg: [[123  43 180 180]]
Faces detected in /content/converted_images/2263.jpg: [[148 162  52  52]]
Faces detected in /content/converted_images/2115.jpg: [[100  69 152 152]]
Faces detected in /content/converted_images/2877.jpg: [[301 153  46  46]
 [232 232 151 151]]
No face detected in /content/converted_images/2537.jpg
No face detected in /content/converted_images/1442.jpg
Faces detected in /content/converted_images/1720.jpg: [[ 92  76 205 205]]
Faces detected in /content/converted_images/240.jpg: [[171  11 164 164]
 [224 182  65  65]]
Faces detected in /content/converted_images/1860.jpg: [[142 105 103 103]]
Faces detected in /content/converted_images/2818.jpg: [[ 60  87 213 213]]
No face detected in /content/converted_images/1839.jpg
No face detected in /content/converted_images/757.jpg
Faces detected in /content/converted_images/129.jpg: [[ 94  89 193 193]]
No face detected in /content/converted_images/2752.jpg
No face detected in /content/converted_images/239.jpg
Faces detected in /content/converted_images/792.jpg: [[ 98  72 198 198]]
Faces detected in /content/converted_images/1895.jpg: [[ 43  73 187 187]]
No face detected in /content/converted_images/1347.jpg
No face detected in /content/converted_images/732.jpg
No face detected in /content/converted_images/2348.jpg
Faces detected in /content/converted_images/2668.jpg: [[182  68 124 124]
 [332 128  65  65]
 [ 71 167  58  58]]
No face detected in /content/converted_images/746.jpg
Faces detected in /content/converted_images/1758.jpg: [[122  87 148 148]]
Faces detected in /content/converted_images/1454.jpg: [[265 146  63  63]
 [111 336  57  57]]
No face detected in /content/converted_images/2429.jpg
Faces detected in /content/converted_images/2273.jpg: [[220  71  66  66]]
Faces detected in /content/converted_images/549.jpg: [[129  46 114 114]]
Faces detected in /content/converted_images/243.jpg: [[124  65 120 120]
 [ 73  66 129 129]]
No face detected in /content/converted_images/309.jpg
Faces detected in /content/converted_images/679.jpg: [[105  95 220 220]]
No face detected in /content/converted_images/2676.jpg
No face detected in /content/converted_images/1871.jpg
Faces detected in /content/converted_images/2793.jpg: [[181  94 212 212]]
No face detected in /content/converted_images/1078.jpg
Faces detected in /content/converted_images/2601.jpg: [[ 96  68 220 220]]
No face detected in /content/converted_images/2460.jpg
Faces detected in /content/converted_images/773.jpg: [[111 108 186 186]]
Faces detected in /content/converted_images/52.jpg: [[ 39  58 304 304]]
No face detected in /content/converted_images/802.jpg
No face detected in /content/converted_images/2409.jpg
No face detected in /content/converted_images/1581.jpg
No face detected in /content/converted_images/836.jpg
Faces detected in /content/converted_images/2411.jpg: [[128  17 100 100]
 [310 343  53  53]]
Faces detected in /content/converted_images/1970.jpg: [[143  72  75  75]]
No face detected in /content/converted_images/1287.jpg
Faces detected in /content/converted_images/1953.jpg: [[  7 117 199 199]]
No face detected in /content/converted_images/1235.jpg
No face detected in /content/converted_images/920.jpg
Faces detected in /content/converted_images/322.jpg: [[105  68 195 195]]
No face detected in /content/converted_images/400.jpg
No face detected in /content/converted_images/562.jpg
No face detected in /content/converted_images/2745.jpg
Faces detected in /content/converted_images/1519.jpg: [[ 30 133  58  58]]
No face detected in /content/converted_images/1124.jpg
No face detected in /content/converted_images/2599.jpg
Faces detected in /content/converted_images/656.jpg: [[ 77  80 200 200]]
No face detected in /content/converted_images/2617.jpg
Faces detected in /content/converted_images/109.jpg: [[ 94  89 193 193]]
Faces detected in /content/converted_images/2222.jpg: [[ 83  77 268 268]]
Faces detected in /content/converted_images/1770.jpg: [[112  92 157 157]]
No face detected in /content/converted_images/1670.jpg
No face detected in /content/converted_images/296.jpg
Faces detected in /content/converted_images/2114.jpg: [[132  73 176 176]]
No face detected in /content/converted_images/1514.jpg
Faces detected in /content/converted_images/325.jpg: [[117  63 192 192]]
No face detected in /content/converted_images/1352.jpg
No face detected in /content/converted_images/2152.jpg
Faces detected in /content/converted_images/2215.jpg: [[ 86  71 193 193]]
Faces detected in /content/converted_images/2299.jpg: [[103   5 161 161]]
Faces detected in /content/converted_images/2086.jpg: [[106  77 167 167]]
No face detected in /content/converted_images/2795.jpg
Faces detected in /content/converted_images/1420.jpg: [[111  54 183 183]]
Faces detected in /content/converted_images/2900.jpg: [[ 82  79 224 224]]
No face detected in /content/converted_images/304.jpg
Faces detected in /content/converted_images/120.jpg: [[ 94  89 193 193]]
No face detected in /content/converted_images/1648.jpg
No face detected in /content/converted_images/1664.jpg
Faces detected in /content/converted_images/476.jpg: [[281 326  57  57]]
Faces detected in /content/converted_images/2595.jpg: [[ 25 150  61  61]]
No face detected in /content/converted_images/1145.jpg
Faces detected in /content/converted_images/2701.jpg: [[107  78 167 167]]
No face detected in /content/converted_images/2688.jpg
Faces detected in /content/converted_images/1772.jpg: [[112  92 157 157]]
No face detected in /content/converted_images/2181.jpg
No face detected in /content/converted_images/2863.jpg
No face detected in /content/converted_images/901.jpg
No face detected in /content/converted_images/1692.jpg
No face detected in /content/converted_images/1216.jpg
No face detected in /content/converted_images/2151.jpg
Faces detected in /content/converted_images/1367.jpg: [[ 56 195  66  66]]
Faces detected in /content/converted_images/1549.jpg: [[271 310  51  51]]
Faces detected in /content/converted_images/1032.jpg: [[ 89  70 168 168]]
No face detected in /content/converted_images/2105.jpg
No face detected in /content/converted_images/2154.jpg
No face detected in /content/converted_images/2261.jpg
No face detected in /content/converted_images/1079.jpg
No face detected in /content/converted_images/165.jpg
Faces detected in /content/converted_images/77.jpg: [[ 94  89 193 193]]
Faces detected in /content/converted_images/1577.jpg: [[168 118  90  90]]
Faces detected in /content/converted_images/1739.jpg: [[ 87  86 191 191]]
Faces detected in /content/converted_images/1681.jpg: [[152 122 103 103]]
No face detected in /content/converted_images/2390.jpg

In [ ]:
df['face_detect'].value_counts()

face_detect
no-face    1550
face       1309
Name: count, dtype: int64

# age detection for all photos

In [ ]:
from deepface import DeepFace
import pandas as pd
import numpy as np

photos_dir = '/content/all_images/all_images' 
output_dir = '/content/resized_images'

os.makedirs(output_dir, exist_ok=True)

# Process all images in the directory
for filename in os.listdir(photos_dir):
    if filename.lower().endswith(('.jpeg', '.jpg', '.png')):  # Process JPEG and PNG files
        img_path = os.path.join(photos_dir, filename)
        img = cv2.imread(img_path)
        if img is not None:
            resized_img = cv2.resize(img, (400, 400))
            new_filename = os.path.splitext(filename)[0] + '.jpg'  # Convert to .jpg
            new_img_path = os.path.join(output_dir, new_filename)
            cv2.imwrite(new_img_path, resized_img)

age_list = []

for index, row in df.iterrows():
    if row['face_detect'] == 'face':
        photo_filename = f"{index}.jpg"  
        photo_path = os.path.join(output_dir, photo_filename)
        try:
            analysis = DeepFace.analyze(img_path=photo_path, actions=['age'])
            formatted_output = analysis[0] if len(analysis) > 0 else {'age': np.nan, 'face_confidence': np.nan}
            age_list.append({'age': formatted_output['age'], 'face_confidence': formatted_output['face_confidence']})
        except Exception as e:
            print(f"Error analyzing sample image {photo_filename}: {e}")
            age_list.append({'age': np.nan, 'face_confidence': np.nan})  # Handle error by setting age and face_confidence to NaN
    else:
        age_list.append({'age': np.nan, 'face_confidence': np.nan})  # Handle case where 'face_detect' is not 'face'

df_result = pd.DataFrame(age_list, columns=['age', 'face_confidence'])

print(df_result)

Error analyzing sample image 24.jpg: Face could not be detected in /content/resized_images222/24.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 33.jpg: Face could not be detected in /content/resized_images222/33.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 47.jpg: Face could not be detected in /content/resized_images222/47.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 54.jpg: Face could not be detected in /content/resized_images222/54.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 139.jpg: Face could not be detected in /content/resized_images222/139.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 145.jpg: Face could not be detected in /content/resized_images222/145.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 170.jpg: Face could not be detected in /content/resized_images222/170.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 171.jpg: Face could not be detected in /content/resized_images222/171.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 172.jpg: Face could not be detected in /content/resized_images222/172.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 178.jpg: Face could not be detected in /content/resized_images222/178.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 190.jpg: Face could not be detected in /content/resized_images222/190.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 203.jpg: Face could not be detected in /content/resized_images222/203.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 217.jpg: Face could not be detected in /content/resized_images222/217.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 219.jpg: Face could not be detected in /content/resized_images222/219.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 229.jpg: Face could not be detected in /content/resized_images222/229.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 237.jpg: Face could not be detected in /content/resized_images222/237.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 260.jpg: Face could not be detected in /content/resized_images222/260.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 262.jpg: Face could not be detected in /content/resized_images222/262.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 263.jpg: Face could not be detected in /content/resized_images222/263.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 279.jpg: Face could not be detected in /content/resized_images222/279.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 280.jpg: Face could not be detected in /content/resized_images222/280.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 281.jpg: Face could not be detected in /content/resized_images222/281.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 285.jpg: Face could not be detected in /content/resized_images222/285.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 307.jpg: Face could not be detected in /content/resized_images222/307.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 319.jpg: Face could not be detected in /content/resized_images222/319.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 344.jpg: Face could not be detected in /content/resized_images222/344.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 391.jpg: Face could not be detected in /content/resized_images222/391.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 418.jpg: Face could not be detected in /content/resized_images222/418.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 420.jpg: Face could not be detected in /content/resized_images222/420.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 423.jpg: Face could not be detected in /content/resized_images222/423.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 441.jpg: Face could not be detected in /content/resized_images222/441.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 446.jpg: Face could not be detected in /content/resized_images222/446.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 455.jpg: Face could not be detected in /content/resized_images222/455.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 476.jpg: Face could not be detected in /content/resized_images222/476.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 477.jpg: Face could not be detected in /content/resized_images222/477.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 479.jpg: Face could not be detected in /content/resized_images222/479.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 494.jpg: Face could not be detected in /content/resized_images222/494.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 520.jpg: Face could not be detected in /content/resized_images222/520.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 529.jpg: Face could not be detected in /content/resized_images222/529.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 530.jpg: Face could not be detected in /content/resized_images222/530.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 534.jpg: Face could not be detected in /content/resized_images222/534.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 535.jpg: Face could not be detected in /content/resized_images222/535.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 536.jpg: Face could not be detected in /content/resized_images222/536.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 543.jpg: Face could not be detected in /content/resized_images222/543.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 546.jpg: Face could not be detected in /content/resized_images222/546.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 569.jpg: Face could not be detected in /content/resized_images222/569.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 570.jpg: Face could not be detected in /content/resized_images222/570.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 571.jpg: Face could not be detected in /content/resized_images222/571.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 572.jpg: Face could not be detected in /content/resized_images222/572.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 605.jpg: Face could not be detected in /content/resized_images222/605.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 627.jpg: Face could not be detected in /content/resized_images222/627.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 662.jpg: Face could not be detected in /content/resized_images222/662.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 664.jpg: Face could not be detected in /content/resized_images222/664.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 673.jpg: Face could not be detected in /content/resized_images222/673.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 688.jpg: Face could not be detected in /content/resized_images222/688.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 689.jpg: Face could not be detected in /content/resized_images222/689.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 707.jpg: Face could not be detected in /content/resized_images222/707.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 708.jpg: Face could not be detected in /content/resized_images222/708.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 720.jpg: Face could not be detected in /content/resized_images222/720.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 733.jpg: Face could not be detected in /content/resized_images222/733.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 747.jpg: Face could not be detected in /content/resized_images222/747.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 748.jpg: Face could not be detected in /content/resized_images222/748.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 749.jpg: Face could not be detected in /content/resized_images222/749.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 775.jpg: Face could not be detected in /content/resized_images222/775.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 785.jpg: Face could not be detected in /content/resized_images222/785.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 788.jpg: Face could not be detected in /content/resized_images222/788.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 796.jpg: Face could not be detected in /content/resized_images222/796.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 813.jpg: Face could not be detected in /content/resized_images222/813.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 863.jpg: Face could not be detected in /content/resized_images222/863.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 877.jpg: Face could not be detected in /content/resized_images222/877.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 888.jpg: Face could not be detected in /content/resized_images222/888.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 899.jpg: Face could not be detected in /content/resized_images222/899.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 905.jpg: Face could not be detected in /content/resized_images222/905.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 909.jpg: Face could not be detected in /content/resized_images222/909.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 913.jpg: Face could not be detected in /content/resized_images222/913.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 919.jpg: Face could not be detected in /content/resized_images222/919.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 936.jpg: Face could not be detected in /content/resized_images222/936.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 939.jpg: Face could not be detected in /content/resized_images222/939.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 951.jpg: Face could not be detected in /content/resized_images222/951.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 952.jpg: Face could not be detected in /content/resized_images222/952.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 976.jpg: Face could not be detected in /content/resized_images222/976.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 985.jpg: Face could not be detected in /content/resized_images222/985.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 991.jpg: Face could not be detected in /content/resized_images222/991.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1010.jpg: Face could not be detected in /content/resized_images222/1010.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1020.jpg: Face could not be detected in /content/resized_images222/1020.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1021.jpg: Face could not be detected in /content/resized_images222/1021.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1022.jpg: Face could not be detected in /content/resized_images222/1022.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1033.jpg: Face could not be detected in /content/resized_images222/1033.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1052.jpg: Face could not be detected in /content/resized_images222/1052.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1064.jpg: Face could not be detected in /content/resized_images222/1064.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1070.jpg: Face could not be detected in /content/resized_images222/1070.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1074.jpg: Face could not be detected in /content/resized_images222/1074.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1103.jpg: Face could not be detected in /content/resized_images222/1103.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1106.jpg: Face could not be detected in /content/resized_images222/1106.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1115.jpg: Face could not be detected in /content/resized_images222/1115.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1116.jpg: Face could not be detected in /content/resized_images222/1116.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1119.jpg: Face could not be detected in /content/resized_images222/1119.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.

In [ ]:
df_result.to_csv('age_deepface.csv', index=False)

Gender Detection

In [ ]:
!pip install pandas deepface opencv-python-headless

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Collecting deepface
  Downloading deepface-0.0.92-py3-none-any.whl (105 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.5/105.5 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: opencv-python-headless in /usr/local/lib/python3.10/dist-packages (4.10.0.82)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: requests>=2.27.1 in /usr/local/lib/python3.10/dist-packages (from deepface) (2.31.0)
Requirement already satisfied: gdown>=3.10.1 in /usr/local/lib/python3.10/dist-packages (from deepface) (5.1.0)
Requirement already satisfied: tqdm>=4.30.0 in /usr/local/lib/python3.10/dist-packages (from deepface) (4.66.4)
Requirement already satisfied: Pillow>=5.2.0 in /usr/local/lib/python3.10/dist-packages (from deepface) (9.4.0)
Requirement already satisfied: opencv-python>=4.5.5.64 in /usr/local/lib/python3.10/dist-packages (from deepface) (4.8.0.76)
Requirement already satisfied: tensorflow>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from deepface) (2.15.0)
Requirement already satisfied: keras>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from deepface) (2.15.0)
Requirement already satisfied: Flask>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from deepface) (2.2.5)
Collecting mtcnn>=0.1.0 (from deepface)
  Downloading mtcnn-0.1.1-py3-none-any.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 30.4 MB/s eta 0:00:00
Collecting retina-face>=0.0.1 (from deepface)
  Downloading retina_face-0.0.17-py3-none-any.whl (25 kB)
Collecting fire>=0.4.0 (from deepface)
  Downloading fire-0.6.0.tar.gz (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.4/88.4 kB 10.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting gunicorn>=20.1.0 (from deepface)
  Downloading gunicorn-22.0.0-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.4/84.4 kB 9.2 MB/s eta 0:00:00
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from fire>=0.4.0->deepface) (1.16.0)
Requirement already satisfied: termcolor in /usr/local/lib/python3.10/dist-packages (from fire>=0.4.0->deepface) (2.4.0)
Requirement already satisfied: Werkzeug>=2.2.2 in /usr/local/lib/python3.10/dist-packages (from Flask>=1.1.2->deepface) (3.0.3)
Requirement already satisfied: Jinja2>=3.0 in /usr/local/lib/python3.10/dist-packages (from Flask>=1.1.2->deepface) (3.1.4)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.10/dist-packages (from Flask>=1.1.2->deepface) (2.2.0)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.10/dist-packages (from Flask>=1.1.2->deepface) (8.1.7)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from gdown>=3.10.1->deepface) (4.12.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from gdown>=3.10.1->deepface) (3.14.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from gunicorn>=20.1.0->deepface) (24.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.27.1->deepface) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.27.1->deepface) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.27.1->deepface) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.27.1->deepface) (2024.6.2)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (0.5.4)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (3.9.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (18.1.1)
Requirement already satisfied: ml-dtypes~=0.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (0.2.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (3.3.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (3.20.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (67.7.2)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (4.12.2)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (0.37.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (1.64.1)
Requirement already satisfied: tensorboard<2.16,>=2.15 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (2.15.2)
Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (2.15.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow>=1.9.0->deepface) (0.43.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2>=3.0->Flask>=1.1.2->deepface) (2.1.5)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (2.27.0)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (1.2.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (3.6)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (0.7.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->gdown>=3.10.1->deepface) (2.5)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from requests>=2.27.1->deepface) (1.7.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (5.3.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (0.4.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (1.3.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (0.6.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (3.2.2)
Building wheels for collected packages: fire
  Building wheel for fire (setup.py) ... done
  Created wheel for fire: filename=fire-0.6.0-py2.py3-none-any.whl size=117029 sha256=f2385b7f3923920f60371abd49a8923b90b767659855a473a93ce0ba2e2b0d7e
  Stored in directory: /root/.cache/pip/wheels/d6/6d/5d/5b73fa0f46d01a793713f8859201361e9e581ced8c75e5c6a3
Successfully built fire
Installing collected packages: gunicorn, fire, mtcnn, retina-face, deepface
Successfully installed deepface-0.0.92 fire-0.6.0 gunicorn-22.0.0 mtcnn-0.1.1 retina-face-0.0.17

In [ ]:
uploaded = files.upload()

# Unzip the uploaded file
for filename in uploaded.keys():
    with zipfile.ZipFile(filename, 'r') as zip_ref:
        zip_ref.extractall('/content/all_images')

Saving all_images.zip to all_images.zip

In [ ]:
from google.colab import files
import zipfile
import os
from deepface import DeepFace


photos_dir = '/content/all_images/all_images'  
output_dir = '/content/resized_images'

os.makedirs(output_dir, exist_ok=True)

# Process all images in the directory
for filename in os.listdir(photos_dir):
    if filename.lower().endswith(('.jpeg', '.jpg', '.png')):  # Process JPEG and PNG files
        img_path = os.path.join(photos_dir, filename)
        img = cv2.imread(img_path)
        if img is not None:
            resized_img = cv2.resize(img, (400, 400))
            new_filename = os.path.splitext(filename)[0] + '.jpg'  # Convert to .jpg
            new_img_path = os.path.join(output_dir, new_filename)
            cv2.imwrite(new_img_path, resized_img)


gender_list = []

for index, row in df.iterrows():
    if row['face_detect'] == 'face':
        photo_filename = f"{index}.jpg"  
        photo_path = os.path.join(output_dir, photo_filename)
        try:
            analysis = DeepFace.analyze(img_path=photo_path, actions=['gender'])
            formatted_output = analysis[0] if len(analysis) > 0 else {'gender': np.nan, 'dominant_gender': np.nan}
            gender_list.append({'gender': formatted_output['gender'], 'dominant_gender': formatted_output['dominant_gender']})
        except Exception as e:
            print(f"Error analyzing sample image {photo_filename}: {e}")
            gender_list.append({'gender': np.nan, 'dominant_gender': np.nan})  # Handle error by setting age and face_confidence to NaN
    else:
        gender_list.append({'gender': np.nan, 'dominant_gender': np.nan})  # Handle case where 'face_detect' is not 'face'


df_result = pd.DataFrame(gender_list, columns=['gender', 'dominant_gender'])

print(df_result)

Error analyzing sample image 24.jpg: Face could not be detected in /content/resized_images4/24.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 33.jpg: Face could not be detected in /content/resized_images4/33.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 47.jpg: Face could not be detected in /content/resized_images4/47.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 54.jpg: Face could not be detected in /content/resized_images4/54.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 139.jpg: Face could not be detected in /content/resized_images4/139.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 145.jpg: Face could not be detected in /content/resized_images4/145.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 170.jpg: Face could not be detected in /content/resized_images4/170.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 171.jpg: Face could not be detected in /content/resized_images4/171.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 172.jpg: Face could not be detected in /content/resized_images4/172.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 178.jpg: Face could not be detected in /content/resized_images4/178.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 190.jpg: Face could not be detected in /content/resized_images4/190.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 203.jpg: Face could not be detected in /content/resized_images4/203.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 217.jpg: Face could not be detected in /content/resized_images4/217.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 219.jpg: Face could not be detected in /content/resized_images4/219.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 229.jpg: Face could not be detected in /content/resized_images4/229.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 237.jpg: Face could not be detected in /content/resized_images4/237.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 260.jpg: Face could not be detected in /content/resized_images4/260.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 262.jpg: Face could not be detected in /content/resized_images4/262.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 263.jpg: Face could not be detected in /content/resized_images4/263.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 279.jpg: Face could not be detected in /content/resized_images4/279.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 280.jpg: Face could not be detected in /content/resized_images4/280.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 281.jpg: Face could not be detected in /content/resized_images4/281.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 285.jpg: Face could not be detected in /content/resized_images4/285.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 307.jpg: Face could not be detected in /content/resized_images4/307.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 319.jpg: Face could not be detected in /content/resized_images4/319.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 344.jpg: Face could not be detected in /content/resized_images4/344.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 391.jpg: Face could not be detected in /content/resized_images4/391.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 418.jpg: Face could not be detected in /content/resized_images4/418.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 420.jpg: Face could not be detected in /content/resized_images4/420.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 423.jpg: Face could not be detected in /content/resized_images4/423.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 441.jpg: Face could not be detected in /content/resized_images4/441.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 446.jpg: Face could not be detected in /content/resized_images4/446.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 455.jpg: Face could not be detected in /content/resized_images4/455.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 476.jpg: Face could not be detected in /content/resized_images4/476.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 477.jpg: Face could not be detected in /content/resized_images4/477.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 479.jpg: Face could not be detected in /content/resized_images4/479.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 494.jpg: Face could not be detected in /content/resized_images4/494.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 520.jpg: Face could not be detected in /content/resized_images4/520.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 529.jpg: Face could not be detected in /content/resized_images4/529.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 530.jpg: Face could not be detected in /content/resized_images4/530.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 534.jpg: Face could not be detected in /content/resized_images4/534.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 535.jpg: Face could not be detected in /content/resized_images4/535.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 536.jpg: Face could not be detected in /content/resized_images4/536.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 543.jpg: Face could not be detected in /content/resized_images4/543.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 546.jpg: Face could not be detected in /content/resized_images4/546.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 569.jpg: Face could not be detected in /content/resized_images4/569.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 570.jpg: Face could not be detected in /content/resized_images4/570.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 571.jpg: Face could not be detected in /content/resized_images4/571.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 572.jpg: Face could not be detected in /content/resized_images4/572.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 605.jpg: Face could not be detected in /content/resized_images4/605.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 627.jpg: Face could not be detected in /content/resized_images4/627.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 662.jpg: Face could not be detected in /content/resized_images4/662.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 664.jpg: Face could not be detected in /content/resized_images4/664.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 673.jpg: Face could not be detected in /content/resized_images4/673.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 688.jpg: Face could not be detected in /content/resized_images4/688.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 689.jpg: Face could not be detected in /content/resized_images4/689.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 707.jpg: Face could not be detected in /content/resized_images4/707.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 708.jpg: Face could not be detected in /content/resized_images4/708.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 720.jpg: Face could not be detected in /content/resized_images4/720.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 733.jpg: Face could not be detected in /content/resized_images4/733.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 747.jpg: Face could not be detected in /content/resized_images4/747.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 748.jpg: Face could not be detected in /content/resized_images4/748.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 749.jpg: Face could not be detected in /content/resized_images4/749.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 775.jpg: Face could not be detected in /content/resized_images4/775.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 785.jpg: Face could not be detected in /content/resized_images4/785.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 788.jpg: Face could not be detected in /content/resized_images4/788.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 796.jpg: Face could not be detected in /content/resized_images4/796.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 813.jpg: Face could not be detected in /content/resized_images4/813.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 863.jpg: Face could not be detected in /content/resized_images4/863.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 877.jpg: Face could not be detected in /content/resized_images4/877.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 888.jpg: Face could not be detected in /content/resized_images4/888.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 899.jpg: Face could not be detected in /content/resized_images4/899.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 905.jpg: Face could not be detected in /content/resized_images4/905.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 909.jpg: Face could not be detected in /content/resized_images4/909.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 913.jpg: Face could not be detected in /content/resized_images4/913.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 919.jpg: Face could not be detected in /content/resized_images4/919.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 936.jpg: Face could not be detected in /content/resized_images4/936.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 939.jpg: Face could not be detected in /content/resized_images4/939.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 951.jpg: Face could not be detected in /content/resized_images4/951.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 952.jpg: Face could not be detected in /content/resized_images4/952.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 976.jpg: Face could not be detected in /content/resized_images4/976.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 985.jpg: Face could not be detected in /content/resized_images4/985.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 991.jpg: Face could not be detected in /content/resized_images4/991.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1010.jpg: Face could not be detected in /content/resized_images4/1010.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1020.jpg: Face could not be detected in /content/resized_images4/1020.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1021.jpg: Face could not be detected in /content/resized_images4/1021.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1022.jpg: Face could not be detected in /content/resized_images4/1022.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1033.jpg: Face could not be detected in /content/resized_images4/1033.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1052.jpg: Face could not be detected in /content/resized_images4/1052.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1064.jpg: Face could not be detected in /content/resized_images4/1064.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1070.jpg: Face could not be detected in /content/resized_images4/1070.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1074.jpg: Face could not be detected in /content/resized_images4/1074.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1103.jpg: Face could not be detected in /content/resized_images4/1103.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1106.jpg: Face could not be detected in /content/resized_images4/1106.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1115.jpg: Face could not be detected in /content/resized_images4/1115.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1116.jpg: Face could not be detected in /content/resized_images4/1116.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1119.jpg: Face could not be detected in /content/resized_images4/1119.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Error analyzing sample image 1131.jpg: Face could not be detected in /content/resized_images4/1131.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.

In [ ]:
df_result

                                                 gender dominant_gender
0     {'Woman': 81.67716264724731, 'Man': 18.3228358...           Woman
1     {'Woman': 81.67716264724731, 'Man': 18.3228358...           Woman
2     {'Woman': 81.67716264724731, 'Man': 18.3228358...           Woman
3                                                   NaN             NaN
4                                                   NaN             NaN
...                                                 ...             ...
2898  {'Woman': 0.3342365147545934, 'Man': 99.665760...             Man
2899                                                NaN             NaN
2900  {'Woman': 2.4515992030501366, 'Man': 97.548395...             Man
2901  {'Woman': 0.8900120854377747, 'Man': 99.109989...             Man
2902                                                NaN             NaN

[2903 rows x 2 columns]

In [ ]:
df_result.to_csv('gender_photo.csv', index=False)